# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MjxowWzZyvA2TLyHqyh4p0XqJIv54DTQ
"""

a = int(input( ' enter 1st number: '))
b = int(input( ' enter 2nd number: '))
c = int(input( ' enter 3 number: '))

if a < c:
    print('a < c')
    print((a * b) + (c - a))
else:
    print('a > c')
    print((a * b) + (a - c))

s = int(input( ' enter 1 number: '))
a = int(input( ' enter 2 number: '))
m = int(input( ' enter 3 number: '))
i = int(input( ' enter 4 number: '))
l = int(input( ' enter 5 number: '))
e = int(input( ' enter 6 number: '))

if (s + a + m) < (i + l + e):
  print('caiu no if')
  print(s + a + m + i + l + e)

else:
  print('caiu no else')
  print(s + a + m) - (i + l + e)

a = int(input( ' enter 1 number: '))
    b = int(input( ' enter 2 number: '))
    c = int(input( ' enter 3 number: '))

    if b > a:
      print('caiu no if')
      print((b / a * c) + ( a - c + b))

    else:
      print('caiu no else')
      print((b * a - c) + (a + c - b))